objects/Archive_Job__c.object
<CustomObject>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Older_Than_Days__c</fullName>
        <label>Older Than Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Archive Job</label>
    <nameField>
        <displayFormat>AJ-{0000}</displayFormat>
        <label>Archive Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archive Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Archive_Job_Item__c.object
<CustomObject>
    <fields>
        <fullName>Range__c</fullName>
        <description>Archive Range. For example date range, ID range, String range, Number range used to archive the records</description>
        <label>Range</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Archive Job Item</label>
    <nameField>
        <displayFormat>AJI-{0000}</displayFormat>
        <label>Archive Job Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archive Job Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ArchiveJobAllocater.cls
public class ArchiveJobAllocater implements Database.Batchable<sObject>{

    Archive_Job__c currentJob;
    
    Public ArchiveJobAllocater(Archive_Job__c aj){
        
    }
    
    Public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('Select '+ String.Join(ApexUtils.getAllFieldsForObject(currentJob.Object_Name__c), ',') +
                                             ' From ' + currentJob.Object_Name__c + 
                                             ' Where CreatedDate<LAST_N_DAYS:'+currentJob.Older_Than_Days__c+
                                             ' Order By Id Asc LIMIT 50000000');
    }
    
    Public void execute(Database.BatchableContext bc, List<sObject> lsObj){
        insert new Archive_Job_Item__c(Range__c=String.valueOf(lsObj.size()));
    }
    
    Public void finish(Database.BatchableContext bc){
        
    }
}