objects/Mass_Report_Download__c.object
<CustomObject>
    <description>Mass Report Download</description>
    <fields>
        <fullName>UserId__c</fullName>
        <description>UserId</description>
        <inlineHelpText>UserId</inlineHelpText>
        <label>UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Mass Report Download</label>
    <nameField>
        <label>Mass Report Download Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Report Downloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassReportsDownloadCtrlrTest.cls
@isTest
public class MassReportsDownloadCtrlrTest {

    private testmethod static void testMassReportDownload(){
        // Load report page
        MassReportsDownloadCtrlr m = new MassReportsDownloadCtrlr();
        System.assert(m.lsReports != Null);
        
        // Save User Selection
        m.saveUserSelection();
        System.assert(![Select Id From Mass_Report_Download__c where UserId__c =: UserInfo.getUserId()].isEmpty());
    }
}