objects/Mass_Report_Download__c.object
<CustomObject>
    <description>Mass Report Download</description>
    <fields>
        <fullName>UserId__c</fullName>
        <description>UserId</description>
        <inlineHelpText>UserId</inlineHelpText>
        <label>UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Selection__c</fullName>
        <description>User Selection</description>
        <inlineHelpText>User Selection</inlineHelpText>
        <label>User Selection</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Mass Report Download</label>
    <nameField>
        <label>Mass Report Download Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mass Report Downloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassReportsDownloadCtrlr.cls
public class MassReportsDownloadCtrlr {
    
    public List<ReportRecord> lsReports {get;set;}
    
    private Mass_Report_Download__c userRecord;
    
    public MassReportsDownloadCtrlr() {
        
        lsReports = new List<ReportRecord>();
        
        // get user selection
        Set<String> selReports = new Set<String>();
        List<Mass_Report_Download__c> lsUserSel = [
            Select 
            	Id, User_Selection__c 
            From 
            	Mass_Report_Download__c 
            Where 
            	UserId__c =: UserInfo.getUserId()];
        if (!lsUserSel.isEmpty() && lsUserSel[0].User_Selection__c != Null) {
            selReports = new Set<String>(lsUserSel[0].User_Selection__c.split(';'));
            userRecord = lsUserSel[0];
        }
        
        // get Records
        for (Report r : [Select Name From Report Where FolderName != Null LIMIT 2000]) {
            lsReports.add(new ReportRecord(r, selReports.contains(r.Id)));
        }
    }
    
    public PageReference saveUserSelection() {
        String userSelected = '';
        for (ReportRecord r : lsReports) {
			if (!r.isSelected) continue;
            
            userSelected += r.rep.Id + ';';
        }
        
        upsert new Mass_Report_Download__c(
            Id = userRecord == Null ? Null : userRecord.Id,
            UserId__c = UserInfo.getUserId(),
            User_Selection__c = userSelected
        );
        
        return Null;
    }
    
    Class ReportRecord {
        public Report rep {get;set;}
        public Boolean isSelected {get;set;}    
        
        public ReportRecord(Report r, Boolean isSelected) {
            this.rep = r;
            this.isSelected = isSelected;
        }
    }
}