objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RemoteController.cls
global class RemoteController {
    
    static global list<merchandise__c> lsGlobMerRecs{get;set;}
    static public list<merchandise__c> lsPubMerRecs{get;set;}
    static private list<merchandise__c> lsPriMerRecs{get;set;}
    
    @RemoteAction
    static global void searchRecords(String searchtext){
        lsPriMerRecs = [Select id, name, price__c from merchandise__c where name like :(searchtext+'%')];
    }
       
    @RemoteAction
    global static list<merchandise__c> getSearchRecords(String searchtext){
        lsGlobMerRecs = [Select id, name, price__c from merchandise__c where name like :(searchtext+'%')];
        lsPubMerRecs = [Select id, name, price__c from merchandise__c where name like :(searchtext+'%')];
        lsPriMerRecs = [Select id, name, price__c from merchandise__c where name like :(searchtext+'%')];
        return lsGlobMerRecs;
    }

}