objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>islaptop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>islaptop</label>
        <type>Checkbox</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/testable.cls
public with sharing class testable {
    
    Public List<Merchandise__c> lsMers{get;set;}
    
    public testable(){
        lsMers = [Select Id, islaptop__c from Merchandise__c];
        System.Debug(Schema.SObjectType.Merchandise__c.Fields.isLaptop__c.isAccessible());
        System.Debug(lsMers);
        System.Debug('Accessible Fields-'+ApexUtils.getAllAccessibleFields('Merchandise__c'));
    }
}