objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <label>Value1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/mytest.cls
@isTest
public class mytest {

    Public Static TestMethod void myTest(){
        System.runAs(TestDataUtils.createUser('Custom: Sales Profile', 'Test')){
            insert new Merchandise__c(Quantity__c = 20, Price__c = 20);
            Merchandise__c m = [Select Id, Quantity__c, Price__c From Merchandise__c LIMIT 1];
            m.value1__c = 20;
        	update m;               
    	}
    }
    
    
    
}