objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/myTestClass5.cls
@isTest global class myTestClass5 {

    @TestVisible
    static integer i=10;
    
    @TestVisible
    static testmethod void func(){
        insert new merchandise__c(name='laptop_modified', price__c=100, Quantity__c=10);
    }
    
    @isTest
    static void func1(){
        Test.startTest();
        system.assertEquals([select id, name from merchandise__c where name='laptop_modified' limit 1].name, 'laptop_modified');
        Test.stopTest();
    }
    
}