objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/myclass_03102016.cls
public with sharing class myclass_03102016 {

    public myclass_03102016(ApexPages.StandardController sc) {
        
        try {
            Merchandise__c m = (Merchandise__c) sc.getRecord();
            m.Quantity__c = 50;

        } catch(Exception e) {
            System.debug('Caught Exception here');
        }
    }
    
    public void onsave() {
            Merchandise__c m1 = [Select Id, Quantity__c From Merchandise__c Where Id =: ApexPages.currentPage().getParameters().get('Id')];
            //m1.Quantity__c = 60;
            update m1;        
    }
    
}