objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Catagories__c</fullName>
        <label>Catagories</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>islaptop__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Charger</fullName>
                </value>
                <value>
                    <fullName>Battery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Merchandise</relationshipLabel>
        <relationshipName>Merchandise</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/merExt2.cls
public class merExt2 {
    
    ApexPages.StandardController cl;
    private List<String> fSets;
    
    public merExt2(ApexPages.StandardController c){
        cl=c;
        fSets = new List<String>{'Id', 'Price__c', 'Quantity__c', 'Invoice__c', 'Catagories__c'};
        cl.addFields(fSets);
    }
    
    public PageReference saveRec(){
        system.debug('SANK-'+((Merchandise__c)cl.getRecord()).Price__c);
        try{
            update cl.getRecord();
        }catch(Exception e){
            ApexPages.addMessages(e);
        }
        
        PageReference redPage = ApexPages.currentPage().getURL().toLowerCase().contains('mytestpage9')?Page.myTestPage8:Page.myTestPage9;
        redPage.getParameters().put('id', cl.getId());
        return redPage;
    }
    
    public List<String> getfieldList(){
        return fSets;
    }
}