objects/Stratics__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Account_id__c</fullName>
        <description>Account id</description>
        <inlineHelpText>Account id</inlineHelpText>
        <label>Account id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Point__c</fullName>
        <description>End Point</description>
        <inlineHelpText>End Point</inlineHelpText>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>api_key__c</fullName>
        <description>api key</description>
        <inlineHelpText>api key</inlineHelpText>
        <label>api key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dnc_type__c</fullName>
        <description>dnc type</description>
        <inlineHelpText>dnc type</inlineHelpText>
        <label>dnc type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isLogSuccess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Do you want to log success ?</description>
        <inlineHelpText>Do you want to log success ?</inlineHelpText>
        <label>Do you want to log success ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>reason__c</fullName>
        <description>reason</description>
        <inlineHelpText>reason</inlineHelpText>
        <label>reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Stratics</label>
</CustomObject>

objects/Stratics_Logs__c.object
<CustomObject>
    <description>Stratics Logs</description>
    <fields>
        <fullName>Is_Success__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Success</description>
        <inlineHelpText>Is Success</inlineHelpText>
        <label>Is Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead</description>
        <inlineHelpText>Lead</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Stratics Logs</relationshipLabel>
        <relationshipName>Stratics_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Sent__c</fullName>
        <description>Request Sent</description>
        <inlineHelpText>Request Sent</inlineHelpText>
        <label>Request Sent</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <description>Response Message</description>
        <inlineHelpText>Response Message</inlineHelpText>
        <label>Response Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Stratics Log</label>
    <nameField>
        <label>Stratics Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stratics Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StraticsUpdate.cls
public class StraticsUpdate {
    
    private static final String end_point = Stratics__c.getInstance().End_Point__c;
    private static final String api_key = Stratics__c.getInstance().api_key__c;
    private static final Boolean isSuccessLoggingEnabled = Stratics__c.getInstance().isLogSuccess__c;
    private static final String accountId = Stratics__c.getInstance().account_id__c;
    private static final String dnctype = Stratics__c.getInstance().dnc_type__c;
    private static final String reason = Stratics__c.getInstance().reason__c;
    private static final Integer MaxCallouts = 100;

    @future(callout=true)
    public static void fireAPI(Set<Id> leadIds) {
        
        // Get all Leads
        List<Lead> lsLeads = getLeads(leadIds);
        
        // Fire 100 call outs (max)
        Integer apiCallMax = lsLeads.size() > MaxCallouts ? MaxCallouts : lsLeads.size();
        List<Stratics_Logs__c> lsLogs = new List<Stratics_Logs__c>();
        for (Integer i = 0; i < apiCallMax; i++) {
        	sendRequest(lsLeads[i], lsLogs);    
        }
        
        if (!lsLogs.isEmpty()) insert lsLogs;
    }
    
    private static List<Lead> getLeads(Set<Id> leadIds) {
        return [Select Id, Phone From Lead Where Id IN :leadIds];
    }
    
    private static void sendRequest(Lead leadObj, List<Stratics_Logs__c> lsLogs) {
        HttpRequest req = new HttpRequest();
        req.setMethod('POST');
        req.setEndpoint(Test.isRunningTest() ? 'http://www.test.com' : end_point);
        req.setHeader('Content-Type', 'application/json');
        req.setBody('{ ' +
        	'"webhook_key": "' + api_key + '",' +            
        	'"account_id": "' + accountId + '",' + 
            '"value": "' + leadObj.Phone + '",' +
            '"dnc_type": "' + dnctype + '",' +
            '"reason": "' + reason + '"' +        
        '}');
        HttpResponse resp = Test.isRunningTest() ? new HttpResponse() : new Http().send(req);
        
        logMessage(leadObj, req, resp, lsLogs);
    }

    private static void logMessage(Lead leadObj, HttpRequest req, HttpResponse resp, List<Stratics_Logs__c> lsLogs) {
        if (resp.getStatusCode() == 200 && !isSuccessLoggingEnabled) return;
        
        lsLogs.add(new Stratics_Logs__c(
            Lead__c = leadObj.Id,  
            Request_Sent__c = req.getBody(), 
            Is_Success__c = resp.getStatusCode() == 200, 
            Response_Message__c = resp.getStatusCode() + ' =' + resp.getBody()
        ));
    }
}